services:
  postgres_orders:
    image: postgres:16
    container_name: postgres_orders
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - postgres_orders_data:/var/lib/postgresql/data

  postgres_payments:
    image: postgres:16
    container_name: postgres_payments
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payments_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - postgres_payments_data:/var/lib/postgresql/data

  broker:
    image: rabbitmq:3-management
    container_name: broker
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # UI
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  orders-service:
    build:
      context: ./orders-service/src/OrdersService
      dockerfile: Dockerfile
    container_name: orders-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__OrdersDb: Host=postgres_orders;Port=5432;Database=orders_db;Username=postgres;Password=postgres
      RabbitMq__Host: broker
      RabbitMq__Port: 5672
      RabbitMq__User: guest
      RabbitMq__Pass: guest
      RabbitMq__Exchange: events
      RabbitMq__RoutingKeyPaymentRequested: payments.payment-requested
      RabbitMq__QueuePaymentResults: orders.payment-results.q
      RabbitMq__RoutingKeyPaymentSucceeded: orders.payment-succeeded
      RabbitMq__RoutingKeyPaymentFailed: orders.payment-failed

    ports:
      - "8081:8080"
    depends_on:
      postgres_orders:
        condition: service_healthy
      broker:
        condition: service_healthy

  payments-service:
    build:
      context: ./payments-service/src/PaymentsService
      dockerfile: Dockerfile
    container_name: payments-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PaymentsDb: Host=postgres_payments;Port=5432;Database=payments_db;Username=postgres;Password=postgres

      RabbitMq__Host: broker
      RabbitMq__Port: 5672
      RabbitMq__User: guest
      RabbitMq__Pass: guest
      RabbitMq__Exchange: events
      RabbitMq__QueuePaymentRequested: payments.payment-requested.q
      RabbitMq__RoutingKeyPaymentRequested: payments.payment-requested
      RabbitMq__RoutingKeyPaymentSucceeded: orders.payment-succeeded
      RabbitMq__RoutingKeyPaymentFailed: orders.payment-failed
    ports:
      - "8082:8080"
    depends_on:
      postgres_payments:
        condition: service_healthy
      broker:
        condition: service_healthy
  gateway:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - orders-service
      - payments-service

  frontend:
    build:
      context: ./frontend
    container_name: frontend
   

volumes:
  postgres_orders_data:
  postgres_payments_data: